exclude: ^tests/resources/
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-merge-conflict
      - id: trailing-whitespace
        exclude: docs/
      - id: mixed-line-ending
      - id: end-of-file-fixer
        exclude: docs/
      - id: check-yaml
        exclude: inference/helm/
      - id: check-ast
        exclude: docs/
  - repo: https://github.com/pycqa/flake8
    rev: 4.0.1
    hooks:
      - id: flake8
        name: Flake8
        description: "Flake8: Your Tool For Style Guide Enforcement"
        entry: flake8 .
        require_serial: true
        types: [ python ]
  - repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
      - id: black
        name: Black
        description: "Black: The uncompromising Python code formatter"
        entry: black
        language: system
        require_serial: true
        types: [ python ]
