name: {{ cookiecutter.repo_name }}
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - pip
  - python=3.8
  - pytest=6.2.2
  - flake8=3.9.2
  - pytest-ordering==0.6
  - black=21.7b0
  - pre-commit=2.9.2
  - pytest-ordering==0.6
  - pip:
    - -e .